from enum import Enum


class WorkflowStatus(str, Enum):

    RECEIVED = "RECEIVED"

    IMAGE_ANALYZED = "IMAGE_ANALYZED"

    ORDER_CREATED = "ORDER_CREATED"

    WAITING_HUMAN_VALIDATION = "WAITING_HUMAN_VALIDATION"

    VALIDATED = "VALIDATED"

    SENT_TO_PLATFORM = "SENT_TO_PLATFORM"

    COMPLETED = "COMPLETED"

    FAILED = "FAILED"